version: 2

jobs:
  build:
    docker:
      - image: brandembassy/php:7.2-fpm-noxdebug

    working_directory: ~/repo

    steps:
      - checkout

      - run: composer install

      - run: composer phpcs
      - run: composer phpstan
      - run: composer phpunit
